server:
  port: 8084

spring:
  application:
    name: room-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/room_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

jwt:
  secret: "your-256-bit-secret-your-256-bit-secret"
  expiration: 86400000

logging:
  level:
    root: WARN
    com.educationalSystem: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logstash:
  host: ${LOGSTASH_HOST:localhost}
  port: ${LOGSTASH_PORT:5000}